### ISSUE TITLE
1.64 

### ISSUE THREAD

**Issue by Pizzaeater103** [ZeddMOCO/GTA-V-Crossmap-1.68#1]
can you please make the crossmap file for 1.64

**Comment by FRIGOSTSTORE1** [comment]
https://www.unknowncheats.me/forum/downloads.php?do=file&id=38792

**Comment by ZeddMOCO** [comment]
update.
https://github.com/ZeddMOCO/GTA-V-Crossmap-1.64/blob/main/crossmap.txt
